kind: Service
apiVersion: v1
metadata:
  name: cortex-distributor
spec:
  selector:
    app: cortex-distributor
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32020
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: cortex-querier
spec:
  selector:
    app: cortex-querier
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32021
  type: NodePort